### ISSUE TITLE
Utils.binarySearch

### ISSUE THREAD

**Issue by shouzhong** [BillyWei01/FastKV#10]
https://github.com/BillyWei01/FastKV/blob/main/FastKV/fastkv/src/main/java/io/fastkv/Util.java#L142
这个方法这步是不是错了，应该是
```
final int midVal = a[mid];
```
![2022 08 08_吴一丰 698e7ee5d9bef2950feb0c59a4812c7a](https://user-images.githubusercontent.com/27850869/183404015-9d0cac0b-dc6d-447a-97f9-0d7f793a1469.png)

**Comment by BillyWei01** [comment]
这是刻意设计成这样子的。所传入的数组，不是[x1, x2, x3...], 而是[x1, y1, x2, y2, x3, y3...]。
折半查找的时候访问的是x1, x2, x3..., 下标为[0,2,4...]，所以需要mid * 2(也就是mid << 1)。
