### ISSUE TITLE
断电之后最后一条数据丢失

### ISSUE THREAD

**Issue by dongdianyi** [BillyWei01/FastKV#12]
您好，没有电池的android设备，put之后，再断电会出现最后一条数据获取不到的情况

**Comment by BillyWei01** [comment]
MMAP的原理就是程序写数据到内存，系统定时刷数据到磁盘。
在put返回的时候，数据写到内存了，但是不一定落到磁盘了。 这是MMAP写入特征，没有办法。
FastKV mmap写入，至少在断电这种case时仅是最后一条数据没有落盘，而不是整个文件损坏。

要想在put完成之后，数据真正写入磁盘，需要“同步写入”。
FastKV支持同步写入的模式，在构建对象的时候调用 blocking() 指定写入模式即可：

```java
FastKV kv = new FastKV.Builder(path, name).blocking().build();
```

只是这种写入模式相对mmap写入要慢不少，但还是比SP的commit模式要快的（快在序列化过程）。

具体使用哪种模式，就看具体需求了。
