### ISSUE TITLE
mmkv如何快速迁移到fastkv

### ISSUE THREAD

**Issue by baolijin** [BillyWei01/FastKV#14]
目前项目遇到数据丢失的问题，key很多不好管理，key分类后一个一个的调用encode来迁移也很麻烦

**Comment by BillyWei01** [comment]
确实没有捷径。
因为MMKV底层存储没有记录value的类型，所以无法直接反序化出所有key-value。
MMKV虽然实现了SharePrefeneces接口，但是 getAll()方案缺没办法实现。
```java
public Map<String, ?> getAll() {
        throw new java.lang.UnsupportedOperationException(
            "Intentionally Not Supported. Use allKeys() instead, getAll() not implement because type-erasure inside mmkv");
 }
```
确实只能如你说说的一个一个调了。
如果觉得太多枚举不全，可以先跳重要的和明显的先迁移（当然还是一次搞定更好一点）。

**Comment by BillyWei01** [comment]
最近想到的迁移MMKV到其他KV的的一种方案：
[FooKV](https://github.com/BillyWei01/FastKV/blob/main/app/src/main/java/io/fastkv/fastkvdemo/storage/FooKV.kt)
