### ISSUE TITLE
java.lang.ClassCastException: io.fastkv.Container$LongContainer cannot be cast to io.fastkv.Container$DoubleContainer

### ISSUE THREAD

**Issue by nbwzlyd** [BillyWei01/FastKV#16]
存储的Long类型，然后将数据全部取出，用Gson转为String存储到txt文件中，再读取回来，putAll，报错了
![image](https://github.com/BillyWei01/FastKV/assets/10379082/8af37929-a615-41da-8a63-3a90a3a4f6b4)
![image](https://github.com/BillyWei01/FastKV/assets/10379082/16d13276-b2be-4c56-abd8-e8acb7a81247)
代码截图如上

**Comment by nbwzlyd** [comment]
数据存储的long，取出来自己变成Double了

**Comment by BillyWei01** [comment]
你从txt再读取回来时的代码是怎么写的？
反序列化的时候这个WARNNING_TEXT_SHOW_TIME的value被解析成Double了吧。

**Comment by nbwzlyd** [comment]
1. FileIOUtils.writeFileFromString(File(root + "hawk"), GsonUtils.toJson(fastKV.all))
2. val data = FileIOUtils.readFile2String(File(root + "hawk"))
            val map = GsonUtils.fromJson<Map<String, Any>>(
                data,
                GsonUtils.getMapType(String::class.java, Any::class.java)
            )
            fastKV.putAll(map)
![image](https://github.com/BillyWei01/FastKV/assets/10379082/65418192-c0af-43c0-8ecc-579959b189ab)

用到了AndroidUtilsCode https://github.com/Blankj/AndroidUtilCode 第三方库，第一步将fastKv中的数据全部取出，转为字符串，存储。第二步，取出数据，把字符串再变成 Map，然后putAll，可参考图片

**Comment by BillyWei01** [comment]
第二部的时候的这个Map的WARNNING_TEXT_SHOW_TIME的value成了Double, 在putAll进去当然也就是Double了。
问题不在 FastKV.putAll这里面，在GsonUtils.fromJson这里。

**Comment by nbwzlyd** [comment]
是的，我测试了下 是Gson导致的，你的库本身没问题。只是不知道你有没有好的方式去兼容该问题，因为这个一旦涉及到数据备份+使用Gson+putLong类型的数据 就会出现该bug。我现在先全部putDouble处理了

**Comment by nbwzlyd** [comment]
找到了个解决方案，但是我没试，是Gson的锅，int会转成double，不仅仅是float，给后来人参考
https://blog.csdn.net/qq_17457105/article/details/89282563
库没问题，我关闭issue了

**Comment by nbwzlyd** [comment]
感谢

**Comment by nbwzlyd** [comment]
GsonBuilder()
            .setObjectToNumberStrategy(ToNumberPolicy.LONG_OR_DOUBLE)
            .create()

**Comment by nbwzlyd** [comment]
// 备份
val kv = new FastKV.Builder(backup_path,  name).asyncBlocking().build();
kv.putAll(map);

// 恢复
val kv = new FastKV.Builder(backup_path,  name).asyncBlocking().build();
val map = kv.getAll();

我用这种方式备份成功了，但是恢复备份的时候，backup_path创建的fastKV,然后getAll是空时咋回事？

**Comment by BillyWei01** [comment]
贴一下代码？

**Comment by nbwzlyd** [comment]
加个QQ？私发你一下，感觉和加密有关

**Comment by BillyWei01** [comment]
最近优化了一下代码：https://juejin.cn/post/7525258095797010482#heading-3
后面如果遇到如上场景，也大概能正确处理。
