### ISSUE TITLE
测试了一下，感觉不大友好，文件大小很容易涨上去吧

### ISSUE THREAD

**Issue by Bter** [BillyWei01/FastKV#18]
![image](https://github.com/BillyWei01/FastKV/assets/20014318/6f8ea30b-691e-44d3-bd6f-df7c2e8b75d6)

![image](https://github.com/BillyWei01/FastKV/assets/20014318/8f59921b-f28b-4a19-bde1-1450245697d1)

**Comment by BillyWei01** [comment]
如果你了解mmap, 那么你会了解mmap申请空间需要申请一个page(4K);
如果你了解磁盘结构，那么你会了解到存储1个字节和存储4K字节，在磁盘都要占用一页（如果一页是4K的话）。

**Comment by BillyWei01** [comment]
<img width="482" alt="4k" src="https://github.com/BillyWei01/FastKV/assets/5714226/9aa0a4c0-ec31-44e8-a5a0-a6a21c70452b">

**Comment by BillyWei01** [comment]
有疑问欢迎加FastKV讨论群：436359235
方便探讨。

**Comment by Kyant0** [comment]
并不一定要全申请一整页吧，可以动态扩容
