### ISSUE TITLE
提一个必现的ANR  case

### ISSUE THREAD

**Issue by Kuki93** [BillyWei01/FastKV#19]
```
class ChannelExecutor(capacity: Int) : Executor {
    private val channel = Channel<Any>(capacity)

    override fun execute(command: Runnable) {
        channel.runBlock {
            command.run()
        }
    }
}

private val UnconfinedCoroutineScope = CoroutineScope(Dispatchers.Unconfined)

private val IOCoroutineScope = CoroutineScope(Dispatchers.IO)

fun Channel<Any>.runBlock(block: suspend CoroutineScope.() -> Unit) {
    UnconfinedCoroutineScope.launch {
        send(0)
        IOCoroutineScope.launch {
            block()
            receive()
        }
    }
}
```

```
fun main() {
    FastKVConfig.setExecutor(ChannelExecutor(4))
    CoroutineScope(Dispatchers.Main.immediate).launch { 
        val faskKV = FastKV.Builder(appContext.cacheDir, "test").build()
        // 这里就不会执行了
        println("")
    }
}
```

**Comment by BillyWei01** [comment]
问题原因:
FastKV 调用[wait()](https://github.com/BillyWei01/FastKV/blob/7942e1a0ef7ed86cc0993fd2f5168ae03f44bb45/fastkv/src/main/java/io/fastkv/FastKV.java#L69)阻塞了当前线程， 然后[notify()](https://github.com/BillyWei01/FastKV/blob/7942e1a0ef7ed86cc0993fd2f5168ae03f44bb45/fastkv/src/main/java/io/fastkv/FastKV.java#L80)在`loadData()`方法中，
`loadData(`需要从传入的Executor中调用`execute`分配线程来执行，`ChannelExecutor(4)` 的 `UnconfinedCoroutineScope`是从当前Scope的线程(也就是Dispatchers.Main.immediate）开始launch,  但是当前线程已经被`wait()`方法block住了，
导致无法走到`notify()`那里…… 

很抱歉ChannelExecutor也是我曾经的用例，现在作茧自缚了……，实在抱歉。

建议：
1、`CoroutineScope(Dispatchers.Main.immediate).launch` 改为 `CoroutineScope(Dispatchers.Main).launch` 可解决此case;
2、`setExecutor` 不再建议调用传入 `ChannelExecutor`，可以直接传入`Dispatchers.Default.asExecutor()`

**Comment by Kuki93** [comment]
那为啥使用`Dispatchers.Main`就没问题

**Comment by Kuki93** [comment]
> 问题原因: FastKV 调用[wait()](https://github.com/BillyWei01/FastKV/blob/7942e1a0ef7ed86cc0993fd2f5168ae03f44bb45/fastkv/src/main/java/io/fastkv/FastKV.java#L69)阻塞了当前线程， 然后[notify()](https://github.com/BillyWei01/FastKV/blob/7942e1a0ef7ed86cc0993fd2f5168ae03f44bb45/fastkv/src/main/java/io/fastkv/FastKV.java#L80)在`loadData()`方法中， `loadData()`需要从传入的Executor中调用`execute`分配线程来执行，`ChannelExecutor(4)` 的 `UnconfinedCoroutineScope`是从当前Scope的线程(也就是Dispatchers.Main.immediate）开始launch, 但是当前线程已经被`wait()`方法block住了， 导致无法走到`notify()`那里……
> 
> 很抱歉ChannelExecutor也是我曾经的用例，现在作茧自缚了……，实在抱歉。
> 
> 建议解决方案： `setExecutor` 不再建议调用传入 `ChannelExecutor`，可以直接传入`Dispatchers.Default.asExecutor()`

我认为使用`Dispatchers.Main.immediate`的时候`loadData`是先执行的，就不会发生`wait`了

**Comment by BillyWei01** [comment]
> 我认为使用`Dispatchers.Main.immediate`的时候`loadData`是先执行的，就不会发生`wait`了

可以加一些log看下执行：

```kotlin
fun Channel<Any>.runBlock(block: suspend CoroutineScope.() -> Unit) {
    Log.d("MyTag", "1")
    UnconfinedCoroutineScope.launch {
        Log.d("MyTag", "2")
        send(0)
        Log.d("MyTag", "3")
        IOCoroutineScope.launch {
            Log.d("MyTag", "4")
            block()
            receive()
            Log.d("MyTag", "5")
        }
        Log.d("MyTag", "6")
    }
    Log.d("MyTag", "7")
}
```

log:
1
7

虽然是使用 `Dispatchers.Main.immediate`， 但 `launch` 还是会挂起Job, 然后launch外的代码先执行。
所以还是会先执行到`wait`。

**Comment by BillyWei01** [comment]
> 那为啥使用`Dispatchers.Main`就没问题

![a](https://github.com/BillyWei01/FastKV/assets/5714226/f05694e7-66c6-4599-9f65-59ff900a9d18)

![b](https://github.com/BillyWei01/FastKV/assets/5714226/d5377919-a08b-44b6-915a-e69af6a032b4)

 1. CoroutineScope(Dispatchers.Main.immediate).launch 的话，launch里面的launch会先不执行;
 2.  CoroutineScope(Dispatchers.Main).launch  的话， launch里面的launch会执行。
 
也就是，CoroutineScope(Dispatchers.Main).launch 使得里面的 CoroutineScope(Dispatchers.IO).launch 能先被执行，从而可以在worker线程中notify主线程的wait方法。
