### ISSUE TITLE
版本问题，无法下载2.4.1

### ISSUE THREAD

**Issue by baihuahuade** [BillyWei01/FastKV#21]
最新是2.4.0还是2.4.1

**Comment by BillyWei01** [comment]
<img width="936" alt="截屏2023-12-05 08 41 52" src="https://github.com/BillyWei01/FastKV/assets/5714226/dc90f83f-10fb-4f41-8f1f-7f6fe8a9ff15">

https://central.sonatype.com/artifact/io.github.billywei01/fastkv?smo=true

2.4.1可以下载，你sync一下？

**Comment by baihuahuade** [comment]
感谢回复，是我的环境问题

**Comment by baihuahuade** [comment]
感谢回复，是我的环境问题
