### ISSUE TITLE
如何查看本地缓存文件内容？

### ISSUE THREAD

**Issue by zengcanxiang** [BillyWei01/FastKV#4]
本地缓存文件一个比较大的需求就是，直接查看文件内容。

使用什么文件查看打开kva、kvb文件比较好呢？使用txt会有很多NULL字符

**Comment by BillyWei01** [comment]
FastKV是用二进制格式存储的，不适合用文本文件打开查看。

FastKV有getAll()接口，返回装有所有key-value的HashMap。
拿到HashMap之后可以直接log出来。

至于“直接查看”，也可以自己编个Java程序来打印key-values， 例如[KVViewer](https://github.com/BillyWei01/FastKV/blob/main/FastKV/src/main/java/io/fastkv/KVViewer.java)。
