### ISSUE TITLE
很棒的模块

### ISSUE THREAD

**Issue by gaoyuoppa** [BillyWei01/FastKV#5]
如果写入的数据是加密的就更棒了.

**Comment by BillyWei01** [comment]
如果有加密的需求，可以先自行加密后在保存。
比方说可以加密成byte[]然后用putArray保存；
也可以自定义一个EncryptEncoder(实现FastKV.Encoder接口）来实现加密。

**Comment by BillyWei01** [comment]
> 如果写入的数据是加密的就更棒了.

最新版本支持了。
