### ISSUE TITLE
关于该框架的商用问题

### ISSUE THREAD

**Issue by Eric-Li-2356** [BillyWei01/FastKV#7]
貌似作者在字节，所以这款框架会用于字节的产品？有计划众测商用吗？

**Comment by BillyWei01** [comment]
字节内部有KV存储库（用C++实现，和MMKV一样需要集成so文件）。
这个lib是个人项目，没有用在字节的产品。

**Comment by BillyWei01** [comment]
快手的广告SDK用了FastKV
