### ISSUE TITLE
对java对象进行ByteArray序列化时putArray时发生异常

### ISSUE THREAD

**Issue by ZXHHYJ** [BillyWei01/FastKV#8]
`   Caused by: java.lang.ClassCastException: io.fastkv.Container$StringContainer cannot be cast to io.fastkv.Container$ArrayContainer
        at io.fastkv.MPFastKV.putArray(MPFastKV.java:502)`
这个`ArrayContainer`是什么？

**Comment by BillyWei01** [comment]
你应该是先putString("key", "some thing"), 然后尝试 putArray("key", array)。
同一个key不能先后保存不同类型，
putArray可以换个key。

**Comment by ZXHHYJ** [comment]
确实是这个问题，已经解决了，感谢
