### ISSUE TITLE
使用了 JDK FileChannel 操作 mmap，貌似没找到 unmap 的地方

### ISSUE THREAD

**Issue by chiclaim** [BillyWei01/FastKV#9]

**Comment by BillyWei01** [comment]
JDK确实没有提供unmap的AP I。
在MappedByteBuffer的注释中是这么写的：
“ A mapped byte buffer and the file mapping that it represents remain valid until the buffer itself is garbage-collected.”
在MappedByteBuffer被GC时会做清理。
